name: CI/CD Development

on:
  workflow_dispatch:  # hanya jalan kalau manual trigger

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Development Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_DEV }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          command_timeout: 15m
          script: |
            cd ~/anitech-general
            git fetch origin development
            git reset --hard origin/development
            docker compose down
            docker compose build --no-cache
            docker compose up -d --wait --wait-timeout 120
            docker image prune -f
            echo "✅ Development deployed!"