name: CI/CD Production

on:
  push:
    branches: [production]
  pull_request:
    types: [closed]
    branches: [production]
  workflow_dispatch:  
jobs:
  build:
    name: Build Check
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  approval:
    name: Waiting for Approval
    needs: build
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Approved
        run: echo "✅ Approved!"

  deploy:
    name: Deploy to Production
    needs: approval
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Production Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          command_timeout: 10m
          script: |
            cd ~/anitech-general
            git fetch origin production
            git reset --hard origin/production
            docker compose down
            docker compose build --no-cache
            docker compose up -d
            docker image prune -f
            echo "🚀 Production deployed!"